title: Ells
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: David Ells # add your name
author-img: ells.jpg # add your photo
about-author: Director of technology at @watershedlrs. Thinker, programmer, appreciator. Proud father and husband. Native and lover of Nashville, TN. # add description
twitter: davidells # add your Twitter handle
facebook: ells.david # add your Facebook handle
github: davidells # add your Github handle
linkedin: david-ells # add your Linkedin handle
email: # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier
sass:
  sass_dir: assets/css/scss/

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
